name: C/C++ CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest
    steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install meson and ninja 
      run: pip install meson ninja
    - uses: actions/checkout@v3
    - name: Run tests 
      run: make test
    - uses: actions/upload-artifact@v3
      with:
        name: Assembly
        path: c#\cpv\cpv\bin\Release\cpv.dll

  build:
    runs-on: windows-latest
    steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install meson and ninja 
      run: pip install meson ninja
    - name: Prepare MSVC
      uses: bus1/cabuild/action/msdevshell@v1
      with:
        architecture: x64
    - name: Setup dotnet
      run: choco install mono
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - uses: actions/checkout@v3
    - name: Build 
      run: make
    - name: Build assembly
      run: msbuild c#\cpv\cpv.sln /property:Configuration=Release
    - uses: actions/upload-artifact@v3
      with:
        name: Library
        path: C:\Program Files\CPV\engine.dll
    - uses: actions/upload-artifact@v3
      with:
        name: Assembly
        path: c#\cpv\cpv\bin\Release\cpv.dll
